sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FuoBVrMJ+MEKoMzpkaBzIvZhv9ej7Js9qfU9we/NOSzRsByPwqMfsNgmN0rdDJeS9CJ0cErvi8gwDY41jVs10zCozYzRZwleAy9EarxBALeAjDj4zq0BnNrHQPfRk/fRGw+4xzx9jC3aKSYDTZe5Uo7blGoYRnkY4mk1PQG44OmhcrsQnGiKKcgJXW5qPVODzUI2kQ0i4CGfl1aW4lyk0VM4JOyoc1CSIvD/5AM0nBxd/avTISN97wW7itJkM0W586a32Sq73fm8D/fN9QWOs8sdVzyapE5YzennL7qAbcOYkkonu41AxKauD5+wvR7t0MqksGePKs1Tyzj5COw6ryIBHIbBg8dTjW/0+xd8hirRAcP9I13NIVq3jGKlG0dcq10r36N8pthu7xzkyf7Ia0yEZVXWKP3vBC093i68SD0Hkn+iFgYv/cPpfN9uPnBPf+Hw6olC9WVXvE/R+xHioNTMYdyYOjY0Fe6w3yxOU1ob9UZr2LxxlxSHTQ2lL+LVypy2+gFNISz+PbWfHSniOMZzIlkirPdAgMllJE5AicWOpG0QiGHGp6oioHQuIaX0WM2gjZAjI5AZOQH8Uc3Vy3EXEreS/LVONv430RkNCIt77+MP26l85IZbEIX3T8sFeOiF8domnT7ep0Jsz0IVeNEzIkH/27Huk5gcrNSPkU4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Over-the-Teacups_2689
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy